/**
 * Submission state machine and execution-claim (lease) logic.
 *
 * Mirrors remote-runtime-business-logic.md sections 12-17 and 73:
 * - status transitions are validated before any state change;
 * - an execution claim atomically moves QUEUED (or RUNNING with an expired
 *   lease) to RUNNING with a fresh execution token and lease deadline;
 * - terminal results commit only when the caller's execution token still
 *   matches, which protects against a stale Worker overwriting a newer
 *   attempt's result.
 */

import type { JudgeAttemptStatus, SubmissionStatus } from "./enums";
import { isTerminalSubmissionStatus } from "./enums";
import type { SubmissionId } from "./ids";

export interface StatusTransition {
  from: ReadonlySet<SubmissionStatus>;
  to: SubmissionStatus;
}

/**
 * Allowed status transitions. CREATED is the API-side pre-queue state,
 * which is why the judge lane's QUEUED -> RUNNING transition still permits
 * CREATED as a source for local rejudge flows.
 *
 * JUDGE_RETRY is the non-terminal infrastructure-retry lane: RUNNING ->
 * JUDGE_RETRY schedules a retry after an infra failure, JUDGE_RETRY (or an
 * expired-lease RUNNING row) -> RUNNING re-claims it on message redelivery,
 * and JUDGE_RETRY -> JUDGE_ERROR terminates it when the retry budget is
 * exhausted. Terminal statuses (including JUDGE_ERROR) never re-enter QUEUED
 * through this table; the admin rejudge path (assertRejudgeTransition) is
 * the only route back.
 */
export const SUBMISSION_TRANSITIONS: readonly StatusTransition[] = [
  { from: new Set(["CREATED", "QUEUED"]), to: "QUEUED" },
  { from: new Set(["CREATED", "QUEUED", "RUNNING", "JUDGE_RETRY"]), to: "RUNNING" },
  { from: new Set(["RUNNING"]), to: "JUDGE_RETRY" },
  {
    from: new Set([
      "RUNNING",
      "CREATED",
      "QUEUED",
      "JUDGE_RETRY",
      "COMPILE_ERROR",
      "WRONG_ANSWER",
      "RUNTIME_ERROR",
      "TIME_LIMIT_EXCEEDED",
      "MEMORY_LIMIT_EXCEEDED",
      "OUTPUT_LIMIT_EXCEEDED",
      "ACCEPTED",
      "JUDGE_ERROR",
    ]),
    to: "JUDGE_ERROR",
  },
  { from: new Set(["RUNNING"]), to: "COMPILE_ERROR" },
  { from: new Set(["RUNNING"]), to: "WRONG_ANSWER" },
  { from: new Set(["RUNNING"]), to: "RUNTIME_ERROR" },
  { from: new Set(["RUNNING"]), to: "TIME_LIMIT_EXCEEDED" },
  { from: new Set(["RUNNING"]), to: "MEMORY_LIMIT_EXCEEDED" },
  { from: new Set(["RUNNING"]), to: "OUTPUT_LIMIT_EXCEEDED" },
  { from: new Set(["RUNNING"]), to: "ACCEPTED" },
];

export function canTransition(from: SubmissionStatus, to: SubmissionStatus): boolean {
  return SUBMISSION_TRANSITIONS.some((t) => t.to === to && t.from.has(from));
}

/**
 * Admin rejudge path: a terminal submission may return to QUEUED so a fresh
 * judge attempt can run. This is intentionally separate from the normal
 * transition table (which keeps terminal states terminal) and from
 * canTransition, so the API lane must opt in explicitly via
 * assertRejudgeTransition.
 */
export const REJUDGE_SOURCES: ReadonlySet<SubmissionStatus> = new Set<SubmissionStatus>([
  "COMPILE_ERROR",
  "WRONG_ANSWER",
  "RUNTIME_ERROR",
  "TIME_LIMIT_EXCEEDED",
  "MEMORY_LIMIT_EXCEEDED",
  "OUTPUT_LIMIT_EXCEEDED",
  "ACCEPTED",
  "JUDGE_ERROR",
]);

export function canRejudgeTransition(from: SubmissionStatus): boolean {
  return REJUDGE_SOURCES.has(from);
}

export function assertRejudgeTransition(from: SubmissionStatus): void {
  if (!canRejudgeTransition(from)) {
    throw new SubmissionTransitionError(from, "QUEUED");
  }
}

export function assertTransition(from: SubmissionStatus, to: SubmissionStatus): void {
  if (!canTransition(from, to)) {
    throw new SubmissionTransitionError(from, to);
  }
}

export class SubmissionTransitionError extends Error {
  readonly from: SubmissionStatus;
  readonly to: SubmissionStatus;

  constructor(from: SubmissionStatus, to: SubmissionStatus) {
    super(`Invalid submission status transition: ${from} -> ${to}`);
    this.name = "SubmissionTransitionError";
    this.from = from;
    this.to = to;
  }
}

export interface ClaimRequest {
  submissionId: SubmissionId;
  /** Fresh token for this execution attempt; generated by the caller (judge lane). */
  executionToken: string;
  /** Absolute epoch-millis deadline for this attempt's lease. */
  leaseUntilMs: number;
  nowMs: number;
}

export interface ClaimResult {
  ok: true;
  /** 1-based attempt number, incremented from the submission's attemptCount. */
  attemptNumber: number;
  status: SubmissionStatus;
}

export interface ClaimRejected {
  ok: false;
  reason: "TERMINAL" | "LEASE_VALID" | "MISSING";
  submissionId: SubmissionId;
}

export type ClaimOutcome = ClaimResult | ClaimRejected;

export function isClaimResult(outcome: ClaimOutcome): outcome is ClaimResult {
  return outcome.ok;
}

export function isClaimRejected(outcome: ClaimOutcome): outcome is ClaimRejected {
  return !outcome.ok;
}

export interface SubmitResultRequest {
  submissionId: SubmissionId;
  /** The token this attempt holds; must still match the stored token. */
  executionToken: string;
  status: SubmissionStatus;
  nowMs: number;
  /** Present only for a successful (ACCEPTED) attempt. */
  performanceScoreNs?: number;
  peakMemoryKb?: number;
  passedTests?: number;
  totalTests?: number;
  /** Storage key of the bounded compiler log; set only for COMPILE_ERROR results. */
  compileLogR2Key?: string;
  /** Ops-facing correlation id; set only for terminal JUDGE_ERROR results. */
  errorId?: string;
}

export type SubmitResultOutcome = "COMMITTED" | "STALE_TOKEN" | "NOT_RUNNING" | "MISSING";

/**
 * A terminal update is accepted only when the caller still holds the
 * current execution token. This is the stale-result protection: a Worker
 * whose lease expired and whose attempt was reclaimed cannot overwrite the
 * newer attempt's result.
 */
export function evaluateResultCommit(
  current: { status: SubmissionStatus; executionToken: string | null },
  request: SubmitResultRequest,
): SubmitResultOutcome {
  if (current.status !== "RUNNING") {
    return "NOT_RUNNING";
  }
  if (current.executionToken === null || current.executionToken !== request.executionToken) {
    return "STALE_TOKEN";
  }
  return "COMMITTED";
}

export const JUDGE_ATTEMPT_TRANSITIONS: readonly { from: ReadonlySet<JudgeAttemptStatus>; to: JudgeAttemptStatus }[] = [
  { from: new Set(["CLAIMED"]), to: "RUNNING" },
  { from: new Set(["CLAIMED", "RUNNING"]), to: "SUCCEEDED" },
  { from: new Set(["CLAIMED", "RUNNING"]), to: "FAILED_RETRYABLE" },
  { from: new Set(["CLAIMED", "RUNNING", "FAILED_RETRYABLE"]), to: "FAILED_TERMINAL" },
];

export function canJudgeAttemptTransition(from: JudgeAttemptStatus, to: JudgeAttemptStatus): boolean {
  return JUDGE_ATTEMPT_TRANSITIONS.some((t) => t.to === to && t.from.has(from));
}

/** Terminal submission statuses never carry an active lease (business-logic invariant B). */
export function assertTerminalHasNoLease(
  status: SubmissionStatus,
  executionToken: string | null,
  leaseUntilMs: number | null,
): void {
  if (isTerminalSubmissionStatus(status) && (executionToken !== null || leaseUntilMs !== null)) {
    throw new Error(`Terminal status ${status} must not hold an execution lease`);
  }
}
